app:
  title: DevPath IDP
  baseUrl: http://localhost:3000

organization:
  name: DevPath

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  endpoints: {}

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  providers:
    guest: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: url
      target: https://github.com/doyindevops/catalog-api-local-4/blob/main/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/doyindevops/gitops-environments/blob/main/catalog-info.yaml
      rules:
        - allow: [Component, System]
